import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Footer from "../components/Footer";
import Feature from "../components/Feature";
import Account from "../components/Account";
import CallToAction from "../components/CallToAction";
// import Reviews from "../components/Reviews";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Header />
      <Hero />
      <Feature />
      <Account />
      <CallToAction />
      {/* <Reviews /> */}
      <Footer />
    </div>
  );
}
